#!/usr/bin/env bash
set -euo pipefail

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PV_GIT_OWNER="${PV_GIT_OWNER:-nova-rey}"
PV_GIT_HOST="${PV_GIT_HOST:-github.com}"
PV_GIT_PROTOCOL="${PV_GIT_PROTOCOL:-https}"

PV_FILE_SERVER_MODE="${PV_FILE_SERVER_MODE:-copyparty}"
PV_FILE_SERVER_PORT="${PV_FILE_SERVER_PORT:-3923}"

PV_INBOX_DIR="${PV_INBOX_DIR:-/srv/prompt-valet/inbox}"
PV_PROCESSED_DIR="${PV_PROCESSED_DIR:-/srv/prompt-valet/processed}"
PV_FINISHED_DIR="${PV_FINISHED_DIR:-/srv/prompt-valet/finished}"
PV_CONFIG_DIR="${PV_CONFIG_DIR:-/srv/prompt-valet/config}"
PV_SCRIPTS_DIR="${PV_SCRIPTS_DIR:-/srv/prompt-valet/scripts}"
PV_LOGS_DIR="${PV_LOGS_DIR:-/srv/prompt-valet/logs}"
PV_BASE_DIR="${PV_BASE_DIR:-/srv/prompt-valet}"
PV_REPOS_DIR="${PV_REPOS_DIR:-/srv/repos}"

PV_RUNNER_CMD="${PV_RUNNER_CMD:-codex}"
PV_RUNNER_EXTRA="${PV_RUNNER_EXTRA:-}"
PV_VALIDATE_ONLY="${PV_VALIDATE_ONLY:-0}"

DRY_RUN=0
if [[ "${PV_VALIDATE_ONLY}" != "0" ]]; then
  DRY_RUN=1
fi

log() {
  printf "[prompt-valet-installer] %s\n" "$*"
}

maybe_run() {
  if ((DRY_RUN)); then
    log "dry-run: $*"
    return 0
  fi
  "$@"
}

ensure_directory() {
  local dir="$1"
  if ((DRY_RUN)); then
    log "dry-run: mkdir -p $dir"
    return 0
  fi
  mkdir -p "$dir"
}

install_packages() {
  if ((DRY_RUN)); then
    log "dry-run: apt-get update"
  else
    DEBIAN_FRONTEND=noninteractive apt-get update
  fi

  local packages=(git python3 python3-venv python3-pip systemd curl)
  if ((DRY_RUN)); then
    log "dry-run: apt-get install -y ${packages[*]}"
  else
    DEBIAN_FRONTEND=noninteractive apt-get install -y "${packages[@]}"
  fi

  if [[ "$PV_FILE_SERVER_MODE" == "copyparty" ]]; then
    if ((DRY_RUN)); then
      log "dry-run: python3 -m pip install --upgrade copyparty"
    else
      python3 -m pip install --upgrade copyparty
    fi
  fi
}

validate_file_server_mode() {
  if [[ "$PV_FILE_SERVER_MODE" != "copyparty" && "$PV_FILE_SERVER_MODE" != "none" ]]; then
    log "error: PV_FILE_SERVER_MODE must be 'copyparty' or 'none'"
    exit 1
  fi
}

clone_or_update_repo() {
  local repo_name="prompt-valet"
  local repo_dir="$PV_REPOS_DIR/$repo_name"
  local repo_url="$PV_GIT_PROTOCOL://$PV_GIT_HOST/$PV_GIT_OWNER/$repo_name.git"

  if [[ -d "$repo_dir/.git" ]]; then
    log "Updating prompt-valet repo at $repo_dir"
    maybe_run git -C "$repo_dir" fetch --all --prune
    if ((DRY_RUN)); then
      log "dry-run: git -C $repo_dir reset --hard origin/HEAD"
    else
      git -C "$repo_dir" reset --hard origin/HEAD >/dev/null
    fi
  else
    log "Cloning prompt-valet repo into $repo_dir"
    maybe_run git clone "$repo_url" "$repo_dir"
  fi
}

deploy_scripts() {
  local source_dir="$SCRIPT_ROOT/scripts"
  local scripts=(codex_watcher.py rebuild_inbox_tree.py)

  for script_name in "${scripts[@]}"; do
    local source_file="$source_dir/$script_name"
    local target_file="$PV_SCRIPTS_DIR/$script_name"
    if ((DRY_RUN)); then
      log "dry-run: copy $source_file -> $target_file"
      continue
    fi
    cp "$source_file" "$target_file"
    chmod 755 "$target_file"
  done
}

write_prompt_valet_config() {
  local config_file="$PV_CONFIG_DIR/prompt-valet.yaml"
  if ((DRY_RUN)); then
    log "dry-run: write prompt-valet config to $config_file"
    return 0
  fi

  cat <<EOF > "$config_file"
# Generated by install_prompt_valet.sh
inbox: "$PV_INBOX_DIR"
processed: "$PV_PROCESSED_DIR"
finished: "$PV_FINISHED_DIR"
repos_root: "$PV_REPOS_DIR"

tree_builder:
  eager_repos: false
  branch_mode: "all"
  branch_whitelist: []
  branch_blacklist: []
  branch_name_blacklist:
    - "HEAD"
  scan_interval_seconds: 60
  greedy_inboxes: false

watcher:
  auto_clone_missing_repos: true
  cleanup_non_git_dirs: true
  git_default_owner: "$PV_GIT_OWNER"
  git_default_host: "$PV_GIT_HOST"
  git_protocol: "$PV_GIT_PROTOCOL"
  runner_cmd: "$PV_RUNNER_CMD"
  runner_extra: "$PV_RUNNER_EXTRA"
  runner_model: "gpt-5.1-codex-mini"
  runner_sandbox: "danger-full-access"
EOF
}

write_copyparty_config() {
  if [[ "$PV_FILE_SERVER_MODE" != "copyparty" ]]; then
    return
  fi

  local copyparty_conf="$PV_BASE_DIR/copyparty.yaml"
  ensure_directory "$PV_LOGS_DIR/copyparty"
  if ((DRY_RUN)); then
    log "dry-run: write copyparty config to $copyparty_conf"
    return 0
  fi

  cat <<EOF > "$copyparty_conf"
# Generated by install_prompt_valet.sh
server:
  address: 0.0.0.0
  port: $PV_FILE_SERVER_PORT
dirs:
  - path: "$PV_INBOX_DIR"
    readonly: true
    label: "Prompt Valet Inbox"
logs:
  root: "$PV_LOGS_DIR/copyparty"
EOF
}

write_service_units() {
  local watcher_unit="/etc/systemd/system/prompt-valet-watcher.service"
  local tree_unit="/etc/systemd/system/prompt-valet-tree-builder.service"
  local timer_unit="/etc/systemd/system/prompt-valet-tree-builder.timer"

  if ((DRY_RUN)); then
    log "dry-run: write $watcher_unit"
  else
    cat <<EOF > "$watcher_unit"
[Unit]
Description=Prompt Valet — Watcher
After=network-online.target

[Service]
ExecStart=/usr/bin/env python3 $PV_SCRIPTS_DIR/codex_watcher.py
WorkingDirectory=$PV_BASE_DIR
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
  fi

  if ((DRY_RUN)); then
    log "dry-run: write $tree_unit"
  else
    cat <<EOF > "$tree_unit"
[Unit]
Description=Prompt Valet — Inbox Tree Builder

[Service]
Type=oneshot
ExecStart=/usr/bin/env python3 $PV_SCRIPTS_DIR/rebuild_inbox_tree.py

[Install]
WantedBy=multi-user.target
EOF
  fi

  if ((DRY_RUN)); then
    log "dry-run: write $timer_unit"
  else
    cat <<EOF > "$timer_unit"
[Unit]
Description=Prompt Valet — Tree Builder Timer

[Timer]
OnCalendar=*:0/5
Unit=prompt-valet-tree-builder.service

[Install]
WantedBy=timers.target
EOF
  fi

  if [[ "$PV_FILE_SERVER_MODE" == "copyparty" ]]; then
    local copyparty_unit="/etc/systemd/system/copyparty.service"
    if ((DRY_RUN)); then
      log "dry-run: write $copyparty_unit"
    else
      cat <<EOF > "$copyparty_unit"
[Unit]
Description=Copyparty — Prompt Valet Inbox
After=network-online.target

[Service]
ExecStart=/usr/bin/env copyparty serve --root $PV_INBOX_DIR --port $PV_FILE_SERVER_PORT --log-dir $PV_LOGS_DIR/copyparty --readonly
WorkingDirectory=$PV_BASE_DIR
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
    fi
  else
    local copyparty_unit="/etc/systemd/system/copyparty.service"
    if ((DRY_RUN)); then
      log "dry-run: remove $copyparty_unit"
    else
      rm -f "$copyparty_unit"
    fi
  fi
}

reload_and_enable_units() {
  if ((DRY_RUN)); then
    log "dry-run: systemctl daemon-reload"
  else
    systemctl daemon-reload
  fi

  if ((DRY_RUN)); then
    log "dry-run: systemctl enable --now prompt-valet-watcher.service"
    log "dry-run: systemctl enable prompt-valet-tree-builder.service"
    log "dry-run: systemctl enable --now prompt-valet-tree-builder.timer"
    log "dry-run: systemctl start prompt-valet-tree-builder.service"
  else
    systemctl enable --now prompt-valet-watcher.service
    systemctl enable prompt-valet-tree-builder.service
    systemctl enable --now prompt-valet-tree-builder.timer
    systemctl start prompt-valet-tree-builder.service
  fi

  if [[ "$PV_FILE_SERVER_MODE" == "copyparty" ]]; then
    if ((DRY_RUN)); then
      log "dry-run: systemctl enable --now copyparty.service"
    else
      systemctl enable --now copyparty.service
    fi
  else
    if ((DRY_RUN)); then
      log "dry-run: systemctl stop --now copyparty.service"
      log "dry-run: systemctl disable copyparty.service"
      log "dry-run: systemctl mask copyparty.service"
    else
      systemctl stop --now copyparty.service >/dev/null 2>&1 || true
      systemctl disable copyparty.service >/dev/null 2>&1 || true
      systemctl mask copyparty.service >/dev/null 2>&1 || true
    fi
  fi
}

main() {
  log "Starting Prompt Valet installer"
  validate_file_server_mode

  local dirs=(
    "$PV_BASE_DIR"
    "$PV_INBOX_DIR"
    "$PV_PROCESSED_DIR"
    "$PV_FINISHED_DIR"
    "$PV_CONFIG_DIR"
    "$PV_SCRIPTS_DIR"
    "$PV_LOGS_DIR"
    "$PV_REPOS_DIR"
  )

  log "Creating directory hierarchy"
  for dir in "${dirs[@]}"; do
    ensure_directory "$dir"
  done

  install_packages
  clone_or_update_repo
  deploy_scripts
  write_prompt_valet_config
  write_copyparty_config
  write_service_units
  reload_and_enable_units

  log "Prompt Valet installer completed"
}

main "$@"
